import createCache from "@emotion/cache";
import { CacheProvider } from "@emotion/react";

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { globalStyles } from "../shared/styles";
import './reset.css'

const cache = createCache({ key: "next" });

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const App = ({ Component, pageProps }) => (
  <CacheProvider value={cache}>
    {globalStyles}
    <Component {...pageProps} />
  </CacheProvider>
);

export default App;
